### ISSUE TITLE
"Target of URI doesn't exist" when importing

### ISSUE THREAD

**Issue by mymikemiller** [rknell/flutterEnumsToString#20]
I have the following in my pubspec.yaml:

```
dependencies:
  enum_to_string: ^1.0.9
```

And the following in a code file:

```
import 'package:enum_to_string:enum_to_string.dart';
```

I run `pub get` in the project without any issues, and I see `Downloading enum_to_string 1.0.9...` in the output, plus the folder `/Users/mikem/.pub-cache/hosted/pub.dartlang.org/enum_to_string-1.0.9` now exists and contains the expected files.

Restarting the IDE (VSCode) does not resolve the problem; I still see the import statement underlined in red, and with the following error:

```
Target of URI doesn't exist: 'package:enum_to_string:enum_to_string.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.
dart(uri_does_not_exist)
```

Do you know why I might be getting this for your library, but not for any others I use?

**Comment by rknell** [comment]
I think this was fixed in this pull request.
https://github.com/rknell/flutterEnumsToString/pull/13

Looks like it was only the example?

Anyway closing for now, if not fixed feel free to ping me and I will investigate further.
