### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by CodeDoctorDE** [rknell/flutterEnumsToString#27]
https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a
It would be cool if this package has null safety support

**Comment by rknell** [comment]
I agree! Have not had a chance to convert it over yet.

**Comment by sameeerkashyap** [comment]
@rknell  if there's no WIP on this, would be happy to make a PR.

**Comment by rknell** [comment]
If you could that would be great thanks! Yeah no WIP so would be happy to accept a PR for it.
